#!/usr/bin/env bun
// Generate routing wrappers, not copies or summaries of workflow logic.
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, join, basename, dirname } from 'node:path';
import { discoverTemplates } from './discover-skills';
import { getHostConfig } from '../hosts/index';

const root = resolve(import.meta.dir, '..');
const outIndex = process.argv.indexOf('--out-dir');
if (outIndex !== -1 && !process.argv[outIndex + 1]) throw new Error('--out-dir needs a path');
const plugin = outIndex === -1 ? join(root, 'plugin/bstack') : resolve(process.argv[outIndex + 1]);
const check = process.argv.includes('--check');
const expected = new Set<string>();
// Freshness mode is read-only, including when an expected file is missing.
function emit(file: string, content: string) {
  if (check) {
    if (!existsSync(file) || readFileSync(file, 'utf8').replaceAll('\r\n', '\n') !== content) {
      throw new Error(`STALE: ${file}; run bun scripts/build-bstack-plugin.ts`);
    }
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}
const runtime = '../../scripts/bstack-runtime.ts';
emit(join(plugin, 'runtime.json'), JSON.stringify({ runtime }, null, 2) + '\n');
// The source tree is a build input. The release packager replaces these
// commands with content-bound launchers rooted at the installed plugin.
const hookCommand = 'powershell.exe -NoProfile -File "${PLUGIN_ROOT}/scripts/bstack.ps1" -Mode hook';
const questionHook = { type: 'command', command: hookCommand.replace('-Mode hook', '-Mode questions'),
  commandWindows: hookCommand.replace('-Mode hook', '-Mode questions'), timeout: 20 };
const questionGroup = { matcher: '(^|[._])request_user_input$', hooks: [questionHook] };
emit(join(plugin, 'hooks/hooks.json'), JSON.stringify({ hooks: { PreToolUse: [{ matcher: '*', hooks: [{
  type: 'command', command: hookCommand, commandWindows: hookCommand, timeout: 30,
}]}, questionGroup], PostToolUse: [questionGroup], Stop: [{ hooks: [{
  type: 'command', command: hookCommand.replace('-Mode hook', '-Mode lifecycle'),
  commandWindows: hookCommand.replace('-Mode hook', '-Mode lifecycle'), timeout: 10,
}]}] } }, null, 2) + '\n');
let count = 0;
for (const { tmpl } of discoverTemplates(root)) {
  const upstreamName = tmpl === 'SKILL.md.tmpl' ? 'gstack' : basename(resolve(root, tmpl, '..'));
  if (getHostConfig('codex').generation.skipSkills?.includes(upstreamName)) continue;
  const name = upstreamName === 'gstack' ? 'bstack' : upstreamName === 'gstack-upgrade' ? 'upgrade' : upstreamName;
  const folder = upstreamName.startsWith('gstack') ? upstreamName : `gstack-${upstreamName}`;
  const rendered = readFileSync(join(root, '.agents/skills', folder, 'SKILL.md'), 'utf8').replaceAll('\r\n', '\n');
  const fm = Bun.YAML.parse(rendered.split('\n---')[0].slice(4)) as { description: string };
  const target = join(plugin, 'skills', name);
  expected.add(name);
  const upgrade = name === 'upgrade' ? `
This is a pinned private downstream fork. Do not execute upstream self-update,
setup, reset, or relink commands. Only on an explicit update request: inspect
the fork's Git state and upstream diff, preserve local patches, integrate on a
separate branch, rebuild, run affected tests and parity gates, then obtain
activation authority. Never update the original gstack installation.
` : `
Read the COMPLETE workflow before acting (continue reading if output truncates):

\`\`\`powershell
& '<this-plugin-root>/scripts/bstack.ps1' -Mode read -Skill ${name}
\`\`\`

The returned generated workflow and its referenced sections own the methodology,
decisions, artifacts, validation and telemetry. Do not replace them with a summary.
`;
  emit(join(target, 'SKILL.md'), `---
name: ${name}
description: ${JSON.stringify(fm.description.trim())}
---
<!-- Generated by scripts/build-bstack-plugin.ts -->
# bstack / ${name}

Resolve <this-plugin-root> as two parents above this SKILL.md's directory.
Read ../../HOST.md first. Use this plugin's workflow namespace for all cross-skill
calls; do not accidentally invoke the old global gstack installation.
${upgrade}
Run Bash blocks through the Windows runtime, from the TASK repository:

\`\`\`powershell
@'
<the workflow's Bash script, unchanged>
'@ | & '<this-plugin-root>/scripts/bstack.ps1' -Mode run
\`\`\`
Each call restores the canonical runtime and state paths. Environment values from
one call do not persist into the next. Keep required SESSION_ID and other emitted
workflow values explicitly. Never convert a failed command into a passing check.
`);
  count++;
}
// Never silently ship retired wrappers, and never delete user-owned additions.
// A failed build is not installable; archive obsolete entries explicitly first.
for (const dir of readdirSync(join(plugin, 'skills'), { withFileTypes: true })) {
  if ((dir.isDirectory() || dir.isSymbolicLink()) && !expected.has(dir.name)) {
    throw new Error(`Obsolete or unowned plugin skill: ${dir.name}; archive it before rebuilding`);
  }
}
console.log(`bstack: ${count} workflow entrypoints ${check ? 'fresh' : 'generated'} at ${plugin}`);
